### ISSUE TITLE
Conflict with old adapter. Pls rename this one because its not compatible to the old one!

### ISSUE THREAD

**Issue by Eistee82** [iobroker-community-adapters/ioBroker.frigate#5]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by mcm1957** [comment]
**This is not a new adapter but a new release of the frigate adapter.** 

Release 1.0.x is a complete rewrite of the prior adapter version. There are incompatible changes - this is noted at releasenotes and indicated by a change in the major version number. Theres no conflict with the older adapter as this release replaces prio release. It's a normel update - although a major update including braking changes.

Adapter release 0.x.x will no longer be maintained by the prior maintainer. Feel free to schedule the update at any time convinient for you. If you miss functionality, please open a feature request.

**Comment by Apollon77** [comment]
maybe a meessage that informs that 1.0.0 is breaking?

**Comment by mcm1957** [comment]
Message ist im io-package drinnen

"Der Adapter hat sich mit v1.0.0 komplett geändert. Alle alten States wurden gelöscht. Bitte überprüfe die Einstellungen und ändere deine Vis und Skripte auf die neuen States. Ringspeicher ist unter events.history. Details findest du in der Readme."

should be sufficient if installed using stadard installation (!= direct github and npm)
